# Generated by Django 5.1.4 on 2026-08-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("teaching", "Enseignement"),
                            ("audio", "Audio"),
                            ("video", "Vidéo"),
                            ("question", "Question"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vue de contenu",
                "verbose_name_plural": "Vues de contenu",
            },
        ),
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("teaching", "Enseignement"),
                            ("audio", "Audio"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_id", models.UUIDField()),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Téléchargement",
                "verbose_name_plural": "Téléchargements",
            },
        ),
    ]
