# Generated by Django 5.1.4 on 2026-08-03 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contentview",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_views",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="downloads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="contentview",
            index=models.Index(
                fields=["content_type", "content_id"],
                name="analytics_c_content_b53f9e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contentview",
            index=models.Index(
                fields=["created_at"], name="analytics_c_created_750b7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["content_type", "content_id"],
                name="analytics_d_content_564ef3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="download",
            index=models.Index(
                fields=["created_at"], name="analytics_d_created_9f1641_idx"
            ),
        ),
    ]
