# Generated by Django 5.1.4 on 2026-08-03 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Teaching",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_fr", models.CharField(max_length=500)),
                ("title_en", models.CharField(blank=True, max_length=500)),
                ("title_ar", models.CharField(blank=True, max_length=500)),
                ("description_fr", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                ("summary_fr", models.TextField(blank=True)),
                ("summary_en", models.TextField(blank=True)),
                ("summary_ar", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="teachings/covers/"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="teachings/pdfs/"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("ar", "العربية"),
                        ],
                        default="fr",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("published", "Publié"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("downloads_count", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Enseignement",
                "verbose_name_plural": "Enseignements",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
