# Generated by Django 5.1.4 on 2026-08-03 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_fr", models.CharField(max_length=500)),
                ("title_en", models.CharField(blank=True, max_length=500)),
                ("title_ar", models.CharField(blank=True, max_length=500)),
                ("description_fr", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("youtube_id", models.CharField(blank=True, max_length=20)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("al_islam", "Al Islam"),
                            ("juste_une_question", "Juste une Question"),
                            ("conferences", "Conférences"),
                            ("interviews", "Interviews"),
                            ("enseignements", "Enseignements"),
                            ("autres", "Autres"),
                        ],
                        default="autres",
                        max_length=50,
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Vidéo",
                "verbose_name_plural": "Vidéos",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
