# Generated by Django 5.1.4 on 2026-08-03 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_fr", models.CharField(max_length=500)),
                ("title_en", models.CharField(blank=True, max_length=500)),
                ("title_ar", models.CharField(blank=True, max_length=500)),
                ("question_fr", models.TextField(blank=True)),
                ("question_en", models.TextField(blank=True)),
                ("question_ar", models.TextField(blank=True)),
                (
                    "keywords",
                    models.TextField(
                        blank=True, help_text="Mots-clés séparés par des virgules"
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question",
                "verbose_name_plural": "Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to="questions/answers/"
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                ("transcript_fr", models.TextField(blank=True)),
                ("transcript_en", models.TextField(blank=True)),
                ("transcript_ar", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("ar", "العربية"),
                        ],
                        default="fr",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "Réponse",
                "verbose_name_plural": "Réponses",
                "ordering": ["created_at"],
            },
        ),
    ]
