# Generated by Django 5.1.4 on 2026-08-03 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_fr", models.CharField(max_length=500)),
                ("title_en", models.CharField(blank=True, max_length=500)),
                ("title_ar", models.CharField(blank=True, max_length=500)),
                ("description_fr", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("book", "Livre"),
                            ("article", "Article"),
                            ("report", "Rapport"),
                            ("brochure", "Brochure"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="documents/covers/"
                    ),
                ),
                ("language", models.CharField(default="fr", max_length=5)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("pages_count", models.PositiveIntegerField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=True)),
                ("downloads_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
            },
        ),
    ]
