# Generated by Django 5.1.4 on 2026-08-03 10:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Audio",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_fr", models.CharField(max_length=500)),
                ("title_en", models.CharField(blank=True, max_length=500)),
                ("title_ar", models.CharField(blank=True, max_length=500)),
                ("description_fr", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("description_ar", models.TextField(blank=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("fr", "Français"),
                            ("en", "English"),
                            ("ar", "العربية"),
                        ],
                        default="fr",
                        max_length=5,
                    ),
                ),
                ("audio_file", models.FileField(upload_to="audios/")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="audios/covers/"
                    ),
                ),
                ("duration", models.DurationField(blank=True, null=True)),
                ("file_size", models.PositiveBigIntegerField(blank=True, null=True)),
                ("plays_count", models.PositiveIntegerField(default=0)),
                ("downloads_count", models.PositiveIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audios",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audio",
                "verbose_name_plural": "Audios",
                "ordering": ["-created_at"],
            },
        ),
    ]
